spring.application.name=ItemCounting
itemcounting.shedule.cron=0 0/2 * * * *
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/itemCounting
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.default_schema=public

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer